import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Database, Info } from 'lucide-react';

const Memory = () => {
  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Memory Log</h2>
          <p className="text-muted-foreground">
            View the session memory that tracks all goals, plans, and results.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Database className="h-5 w-5" />
              Session Memory
            </CardTitle>
            <CardDescription>
              Memory is stored in browser session and resets on page refresh.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex items-start gap-3 p-4 rounded-lg bg-muted/50">
              <Info className="h-5 w-5 text-blue-500 mt-0.5" />
              <div className="space-y-2 text-sm">
                <p>
                  The Memory Module is a core component of the Agentic AI architecture. 
                  It stores:
                </p>
                <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                  <li>Goals submitted by users</li>
                  <li>Sub-task plans generated by the Planner</li>
                  <li>Execution results from the Executor</li>
                  <li>Critique feedback from the Critic</li>
                  <li>Refined outputs after improvement cycles</li>
                </ul>
                <p className="text-muted-foreground mt-2">
                  In this prototype, memory is session-based. In a production system, 
                  this would persist to a database for cross-session continuity.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default Memory;
